spring:

  application:
    name: ${APPLICATION_NAME:cent}

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/cent?currentSchema=${spring.application.name}}
    username: ${DB_LOGIN:postgres}
    password: ${DB_PASSWORD:password}
